[package]
name = "ttf-firacode"
version = "0.1.0"
authors = ["l1h3r <devin.turner09@gmail.com>"]
edition = "2018"

[dependencies]

[features]
default = ["regular"]
bold = []
light = []
medium = []
regular = []
retina = []
